export const CodigoDeErro = {
  REQUISICAO_INVALIDA: "REQUISICAO_INVALIDA",
  NAO_AUTORIZADO: "NAO_AUTORIZADO",
  PROIBIDO: "PROIBIDO",
  NAO_ENCONTRADO: "NAO_ENCONTRADO",
  ERRO_INTERNO: "ERRO_INTERNO",
  ERRO_DOWNSTREAM: "ERRO_DOWNSTREAM",
  TIMEOUT_DOWNSTREAM: "TIMEOUT_DOWNSTREAM",
  IA_INDISPONIVEL: "IA_INDISPONIVEL",
} as const;

export type ValorCodigoDeErro = (typeof CodigoDeErro)[keyof typeof CodigoDeErro];
